
SCREEN_SIZE = (800, 600)
FRAME_RATE = 60
GLOBAL_STYLE_DICT = "default"
GLOBAL_RESOURCE_DICT = "r_dict"
START_ENVIRONMENT = "sprite_demo"
EVENT_NAME_LOGGER = 0
REPR_SIG_FIGS = 3
TRANSITION_TIME = 6
TEXT_ANTI_ALIAS = 1
DIALOG_POSITION = (300, 300)
CONTROLLERS = ("dev_mode",)


